// Code generated by "stringer -type Token"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ILLEGAL-0]
	_ = x[EOF-1]
	_ = x[COMMENT-2]
	_ = x[NAME-3]
	_ = x[INT-4]
	_ = x[FLOAT-5]
	_ = x[STRING-6]
	_ = x[LPAREN-7]
	_ = x[LBRACK-8]
	_ = x[LBRACE-9]
	_ = x[RPAREN-10]
	_ = x[RBRACK-11]
	_ = x[RBRACE-12]
	_ = x[LT-13]
	_ = x[GT-14]
	_ = x[LSHIFT-15]
	_ = x[RSHIFT-16]
	_ = x[SLASH-17]
	_ = x[SLASHSLASH-18]
}

const _Token_name = "ILLEGALEOFCOMMENTNAMEINTFLOATSTRINGLPARENLBRACKLBRACERPARENRBRACKRBRACELTGTLSHIFTRSHIFTSLASHSLASHSLASH"

var _Token_index = [...]uint8{0, 7, 10, 17, 21, 24, 29, 35, 41, 47, 53, 59, 65, 71, 73, 75, 81, 87, 92, 102}

func (i Token) String() string {
	if i < 0 || i >= Token(len(_Token_index)-1) {
		return "Token(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
